apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hpe01-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Hpe01-demo
  template:
    metadata:
      labels:
        app: Hpe01-demo
    spec:
      containers:
        - name: Hpe
          image: kandula435/docker-web-demo:docker-web-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: Hpe01-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: Hpe01-demo
